version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    allow:
      - dependency-type: 'direct'
    groups:
      minor-and-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
