backend:
  name: github
  repo: mick-schroeder/news.mickschroeder.com
  branch: main
  auth_scope: public_repo
  app_id: "Ov23lilL0a2MeZH9wzJP"
  base_url: "https://auth.mickschroeder.com"
  auth_endpoint: "/auth"
media_folder: "static/screenshots"
site_url: "https://news.mickschroeder.com"
display_url: "https://news.mickschroeder.com"
omit_empty_optional_fields: true
show_preview_links: false

media_folder: "static/screenshots"

site_url: "https://news.mickschroeder.com"
display_url: "https://news.mickschroeder.com"

collections:
  - name: "sources"
    label: "News Sources"
    label_singular: "News Source"
    description: "Edit news sources list for the app"
    files:
    - name: "sources-json"
      label: "All News Sources"
      file: "src/data/data.json"
      format: "json"
      fields:
        - label: "News Sources"
          name: "sources"
          widget: "list"
          label_singular: "News Source"
          summary: "{{fields.name}} ({{fields.url}}) {{fields.categories | join(', ')}} (⭐ {{fields.score}})"
          collapsed: true
          add_to_top: true
          sortable: true
          fields:
            - { label: "Name", name: "name", widget: "string", hint: "Publisher or site name (e.g., AP News)" }
            - label: "URL"
              name: "url"
              widget: "string"
              hint: "Full homepage URL (https preferred)"
              pattern:
                - "^https?://.+"
                - "Must start with http(s)://"
            - label: "Categories"
              name: "categories"
              widget: "list"
              summary: "{{fields.item}}"
              field:
                { label: "Category", name: "item", widget: "string", hint: "e.g., Global, American, Irish" }
              add_to_top: true
              allow_add: true
            - label: "Score"
              name: "score"
              widget: "number"
              value_type: "float"
              min: 0
              max: 5
              step: 0.1
              hint: "0–5 impact score (one decimal)"
