export const SCRAPERS = [
  {
    id: 'drudgereport',
    label: 'Drudge Report',
    url: 'https://www.drudgereport.com/',
    internalUrls: ['https://www.drudgereport.com/', 'https://drudgereport.com/'],
    pinnedSources: [
      {
        canonicalKey: 'drudgereport.com',
        name: 'Drudge Report',
        url: 'https://drudgereport.com/',
        tags: ['Aggregator'],
      },
    ],
  },
  {
    id: 'skimfeed-news',
    label: 'Skimfeed · News',
    url: 'https://skimfeed.com/news.html',
    internalUrls: ['https://skimfeed.com/'],
    tags: ['News'],
  },
  {
    id: 'skimfeed-tech',
    label: 'Skimfeed · Tech',
    url: 'https://skimfeed.com/tech.html',
    internalUrls: ['https://skimfeed.com/'],
    tags: ['Tech'],
  },
  {
    id: 'skimfeed-politics',
    label: 'Skimfeed · Politics',
    url: 'https://skimfeed.com/politics.html',
    internalUrls: ['https://skimfeed.com/'],
    tags: ['Politics'],
  },
  {
    id: 'skimfeed-science',
    label: 'Skimfeed · Science',
    url: 'https://skimfeed.com/science.html',
    internalUrls: ['https://skimfeed.com/'],
    tags: ['Science'],
  },
  {
    id: 'skimfeed-agg',
    label: 'Skimfeed · Aggregators',
    url: 'https://skimfeed.com/agg.html',
    internalUrls: ['https://skimfeed.com/'],
    tags: ['Aggregator'],
  },
  {
    id: 'realclearpolitics',
    label: 'RealClearPolitics',
    url: 'https://www.realclearpolitics.com/',
    internalUrls: ['https://www.realclearpolitics.com/', 'https://realclearpolitics.com/'],
  },
  {
    id: 'techmeme',
    label: 'Techmeme',
    url: 'https://www.techmeme.com/lb.opml',
    internalUrls: ['https://www.techmeme.com/', 'https://techmeme.com/'],
    sourceOpml: true,
    maxSourceCandidates: 50,
  },
  {
    id: 'memeorandum',
    label: 'Memeorandum',
    url: 'https://www.memeorandum.com/lb.opml',
    internalUrls: ['https://www.memeorandum.com/', 'https://memeorandum.com/'],
    sourceOpml: true,
    maxSourceCandidates: 50,
  },
  {
    id: 'mediagazer',
    label: 'Mediagazer',
    url: 'https://mediagazer.com/lb.opml',
    internalUrls: ['https://mediagazer.com/', 'https://www.mediagazer.com/'],
    sourceOpml: true,
    maxSourceCandidates: 50,
  },
  {
    id: 'brutalist-news',
    label: 'Brutalist · News',
    url: 'https://brutalist.report/topic/news',
    internalUrls: ['https://brutalist.report/'],
    sourceSectionLinks: true,
    tags: ['News'],
    pinnedSources: [
      {
        canonicalKey: 'brutalist.report',
        name: 'The Brutalist Report',
        url: 'https://brutalist.report/',
        tags: ['Aggregator'],
      },
    ],
  },
  {
    id: 'brutalist-tech',
    label: 'Brutalist · Tech',
    url: 'https://brutalist.report/topic/tech',
    internalUrls: ['https://brutalist.report/'],
    sourceSectionLinks: true,
    tags: ['Tech'],
  },
  {
    id: 'brutalist-business',
    label: 'Brutalist · Business',
    url: 'https://brutalist.report/topic/business',
    internalUrls: ['https://brutalist.report/'],
    sourceSectionLinks: true,
    tags: ['Business'],
  },
  {
    id: 'brutalist-science',
    label: 'Brutalist · Science',
    url: 'https://brutalist.report/topic/science',
    internalUrls: ['https://brutalist.report/'],
    sourceSectionLinks: true,
    tags: ['Science'],
  },
  {
    id: 'brutalist-gaming',
    label: 'Brutalist · Gaming',
    url: 'https://brutalist.report/topic/gaming',
    internalUrls: ['https://brutalist.report/'],
    sourceSectionLinks: true,
    tags: ['Gaming'],
  },
  {
    id: 'brutalist-culture',
    label: 'Brutalist · Culture',
    url: 'https://brutalist.report/topic/culture',
    internalUrls: ['https://brutalist.report/'],
    sourceSectionLinks: true,
    tags: ['Culture'],
  },
  {
    id: 'brutalist-politics',
    label: 'Brutalist · Politics',
    url: 'https://brutalist.report/topic/politics',
    internalUrls: ['https://brutalist.report/'],
    sourceSectionLinks: true,
    tags: ['Politics'],
  },
  {
    id: 'clone-fyi',
    label: 'clone.fyi',
    url: 'https://clone.fyi/api/content/agent',
    internalUrls: ['https://clone.fyi/'],
    sourceJson: true,
    pinnedSources: [
      {
        canonicalKey: 'clone.fyi',
        name: 'clone.fyi',
        url: 'https://clone.fyi/',
        tags: ['Aggregator', 'News'],
      },
    ],
    tags: ['News'],
  },
];

export const getScraperById = (id) => SCRAPERS.find((scraper) => scraper.id === id);
